apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: gcr.io/PROJECT_ID/IMAGE
  newName: gcr.io/${PROJECT_ID}/${IMAGE}
  newTag: ${GITHUB_SHA}
