NodeVersion="20.18.0"
nodeBuildCommandsFile="/tmp/zipdeploy/extracted/oryx-build-commands.txt"
Frameworks="Typescript,Next.js"
compressedNodeModulesFile="node_modules.tar.gz"
OutputDirPath=".next"
OperationId="574455d1cb34df44"
SourceDirectoryInBuildContainer="/tmp/8dd20bbec07ffd7"
PlatformName="nodejs,python,php"
CompressDestinationDir="false"
